import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="bg-gradient-to-r from-purple-200 via-purple-400 to-purple-900">
        {children}
      </body>
    </html>
  );
}
